{% set name = "types-geoip2" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-geoip2-{{ version }}.tar.gz
  sha256: 75ce236f3d98529b44b2dddf91476178ff0d088f33414b206253594936613574

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - types-maxminddb

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/geoip2-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for geoip2
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
